#!/usr/bin/env node

var createPage = require('./lib/createPage');
var updatePage = require('./lib/updatePage');
var updateWidget = require('./lib/updateWidget');
var createWidget = require('./lib/createWidget');

var argv = process.argv;

var url = "https://flag-embraer.qa.nodo.cc/";

if(argv[2] == 'help') {

    console.log("\n\n          -- CHONGLY --  Version 0.4.1\n");
    console.log("chongly new page {page.json} - Creates a new page");
    console.log("chongly update page {pageId} {update.json} - Update page");
    console.log("chongly new widget {widget.json} - Creates a new widget");
    console.log("chongly update widget {widgetId} {update.json} - Update widget\n\n");

    return;
}

if(argv[2] == 'new') {
    if(argv[3] == 'page'){

        createPage(require('./' + argv[4]), url);

    }

    if(argv[3] == 'widget'){
        
        createWidget(require('./' + argv[4]), url);

    }
}

if(argv[2] == 'update') {

    if(argv[3] == 'page') {

        updatePage(require('./' + argv[5]), argv[4], url);

    }

    if(argv[3] == 'widget') {

        updateWidget(require('./' + argv[5]), argv[4], url);

    }
}

